erp_mpro/apps/base/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path
from . import views

from erp_mpro.configs import DEBUG

app_name = 'base'
urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
]

if DEBUG:
    urlpatterns += [
        re_path(r'^404/$', views.handler404),
        re_path(r'^500/$', views.handler500),
    ]

erp_mpro/apps/estoque/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path
from . import views

app_name = 'estoque'
urlpatterns = [
    # Consulta de estoque
    # estoque/consultaestoque/
    re_path(r'consultaestoque/$', views.ConsultaEstoqueView.as_view(),
        name='consultaestoqueview'),

    # Local de estoque
    # estoque/local/adicionar/
    re_path(r'local/saida/adicionar/$',
        views.AdicionarLocalEstoqueView.as_view(), name='addlocalview'),
    # estoque/local/listalocal
    re_path(r'local/listalocal/$', views.LocalEstoqueListView.as_view(),
        name='listalocalview'),
    # estoque/local/editar/
    re_path(r'local/editar/(?P<pk>[0-9]+)/$',
        views.EditarLocalEstoqueView.as_view(), name='editarlocalview'),

    # Movimento de estoque
    # Lista todos movimentos
    re_path(r'movimentos/$', views.MovimentoEstoqueListView.as_view(),
        name='listamovimentoestoqueview'),

    # EntradaEstoque
    # estoque/movimento/adicionarentrada/
    re_path(r'movimento/adicionarentrada/$',
        views.AdicionarEntradaEstoqueView.as_view(), name='addentradaestoqueview'),
    # estoque/movimento/listaentradas/
    re_path(r'movimento/listaentradas/$', views.EntradaEstoqueListView.as_view(),
        name='listaentradasestoqueview'),
    # estoque/movimento/editarentrada/
    re_path(r'movimento/editarentrada/(?P<pk>[0-9]+)/$', views.DetalharEntradaEstoqueView.as_view(
    ), name='detalharentradaestoqueview'),

    # SaidaEstoque
    # estoque/movimento/adicionarsaida/
    re_path(r'movimento/adicionarsaida/$',
        views.AdicionarSaidaEstoqueView.as_view(), name='addsaidaestoqueview'),
    # estoque/movimento/listasaidas/
    re_path(r'movimento/listasaidas/$', views.SaidaEstoqueListView.as_view(),
        name='listasaidasestoqueview'),
    # estoque/movimento/editarsaida/
    re_path(r'movimento/editarsaida/(?P<pk>[0-9]+)/$',
        views.DetalharSaidaEstoqueView.as_view(), name='detalharsaidaestoqueview'),

    # TransferenciaEstoque
    # estoque/movimento/adicionartransferencia/
    re_path(r'movimento/adicionartransferencia/$',
        views.AdicionarTransferenciaEstoqueView.as_view(), name='addtransferenciaestoqueview'),
    # estoque/movimento/listatransferencias/
    re_path(r'movimento/listatransferencias/$', views.TransferenciaEstoqueListView.as_view(),
        name='listatransferenciasestoqueview'),
    # estoque/movimento/editartransferencia/
    re_path(r'movimento/editartransferencia/(?P<pk>[0-9]+)/$', views.DetalharTransferenciaEstoqueView.as_view(
    ), name='detalhartransferenciaestoqueview'),
]

erp_mpro/apps/fiscal/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path
from . import views

app_name = 'fiscal'
urlpatterns = [
    # Nota fiscal saida
    # fiscal/notafiscal/saida/adicionar/
    re_path(r'notafiscal/saida/adicionar/$',
        views.AdicionarNotaFiscalSaidaView.as_view(), name='addnotafiscalsaidaview'),
    # fiscal/notafiscal/saida/listanotafiscal
    re_path(r'notafiscal/saida/listanotafiscal/$',
        views.NotaFiscalSaidaListView.as_view(), name='listanotafiscalsaidaview'),
    # fiscal/notafiscal/saida/editar/
    re_path(r'notafiscal/saida/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalSaidaView.as_view(
    ), name='editarnotafiscalsaidaview'),
    # fiscal/notafiscal/saida/importar/
    re_path(r'notafiscal/saida/importar/$',
        views.ImportarNotaSaidaView.as_view(), name='importarnotafiscalsaida'),
    # fiscal/notafiscal/saida/gerar/
    re_path(r'notafiscal/saida/gerar/(?P<pk>[0-9]+)/$',
        views.GerarNotaFiscalSaidaView.as_view(), name='gerarnotafiscalsaida'),

    # Nota fiscal entrada
    # fiscal/notafiscal/entrada/listanotafiscal
    re_path(r'notafiscal/entrada/listanotafiscal/$',
        views.NotaFiscalEntradaListView.as_view(), name='listanotafiscalentradaview'),
    # fiscal/notafiscal/entrada/editar/
    re_path(r'notafiscal/entrada/editar/(?P<pk>[0-9]+)/$', views.EditarNotaFiscalEntradaView.as_view(
    ), name='editarnotafiscalentradaview'),
    # fiscal/notafiscal/entrada/importar/
    re_path(r'notafiscal/entrada/importar/$',
        views.ImportarNotaEntradaView.as_view(), name='importarnotafiscalentrada'),

    # Configuracao NF-e
    re_path(r'notafiscal/configuracaonotafiscal/$',
        views.ConfiguracaoNotaFiscalView.as_view(), name='configuracaonotafiscal'),

    # Natureza operacao
    # fiscal/naturezaoperacao/adicionar/
    re_path(r'naturezaoperacao/adicionar/$',
        views.AdicionarNaturezaOperacaoView.as_view(), name='addnaturezaoperacaoview'),
    # fiscal/naturezaoperacao/listanaturezaoperacao
    re_path(r'naturezaoperacao/listanaturezaoperacao/$',
        views.NaturezaOperacaoListView.as_view(), name='listanaturezaoperacaoview'),
    # fiscal/naturezaoperacao/editar/
    re_path(r'naturezaoperacao/editar/(?P<pk>[0-9]+)/$', views.EditarNaturezaOperacaoView.as_view(
    ), name='editarnaturezaoperacaoview'),

    # Grupo fiscal
    # fiscal/grupofiscal/adicionar/
    re_path(r'grupofiscal/adicionar/$',
        views.AdicionarGrupoFiscalView.as_view(), name='addgrupofiscalview'),
    # fiscal/grupofiscal/listagrupofiscalview
    re_path(r'grupofiscal/listagrupofiscal/$',
        views.GrupoFiscalListView.as_view(), name='listagrupofiscalview'),
    # fiscal/grupofiscal/editar/
    re_path(r'grupofiscal/editar/(?P<pk>[0-9]+)/$',
        views.EditarGrupoFiscalView.as_view(), name='editargrupofiscalview'),

    # Acoes Nota Fiscal
    # Validar XML nota
    re_path(r'notafiscal/validar/(?P<pk>[0-9]+)/$',
        views.ValidarNotaView.as_view(), name='validarnotafiscal'),
    # fiscal/notafiscal/emitir/
    re_path(r'notafiscal/emitir/(?P<pk>[0-9]+)/$',
        views.EmitirNotaView.as_view(), name='emitirnotafiscal'),
    # Clonar nota
    re_path(r'notafiscal/copiar/(?P<pk>[0-9]+)/$',
        views.GerarCopiaNotaView.as_view(), name='copiarnotafiscal'),
    # Cancelar nota
    re_path(r'notafiscal/cancelar/(?P<pk>[0-9]+)/$',
        views.CancelarNotaView.as_view(), name='cancelarnotafiscal'),
    # Gerar DANFE
    re_path(r'notafiscal/gerardanfe/(?P<pk>[0-9]+)/$',
        views.GerarDanfeView.as_view(), name='gerardanfe'),
    # Gerar DANFCE
    re_path(r'notafiscal/gerardanfce/(?P<pk>[0-9]+)/$',
        views.GerarDanfceView.as_view(), name='gerardanfce'),

    # Comunicacao SEFAZ
    # Consultar cadastro
    re_path(r'notafiscal/consultarcadastro/$',
        views.ConsultarCadastroView.as_view(), name='consultarcadastro'),
    # Inutilizar notas
    re_path(r'notafiscal/inutilizarnotas/$',
        views.InutilizarNotasView.as_view(), name='inutilizarnotas'),
    # Consultar nota
    re_path(r'notafiscal/consultarnota/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    re_path(r'^notafiscal/consultarnota/(?P<pk>[0-9]+)/$',
        views.ConsultarNotaView.as_view(), name='consultarnota'),
    # Baixar nota
    re_path(r'notafiscal/baixarnota/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    re_path(r'^notafiscal/baixarnota/(?P<pk>[0-9]+)/$',
        views.BaixarNotaView.as_view(), name='baixarnota'),
    # Manifestacao destinatario
    re_path(r'notafiscal/manifestacaodestinatario/$',
        views.ManifestacaoDestinatarioView.as_view(), name='manifestacaodestinatario'),
]

erp_mpro/apps/login/urls.py
from django.urls import re_path
from . import views

app_name = 'login'
urlpatterns = [
    # login/
    re_path(r'^$', views.UserFormView.as_view(), name='loginview'),

    # login/registrar/
    re_path(r'registrar/$', views.UserRegistrationFormView.as_view(),
        name='registrarview'),

    # login/esqueceu/:
    re_path(r'^esqueceu/$', views.ForgotPasswordView.as_view(), name='esqueceuview'),

    # login/trocarsenha/:
    re_path(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        views.PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    re_path(r'^logout/$', views.UserLogoutView.as_view(), name='logoutview'),

    # login/perfil/
    re_path(r'^perfil/$', views.MeuPerfilView.as_view(), name='perfilview'),

    # login/editarperfil/
    re_path(r'^editarperfil/$', views.EditarPerfilView.as_view(), name='editarperfilview'),

    # login/usuarios/
    re_path(r'^usuarios/$', views.UsuariosListView.as_view(), name='usuariosview'),

    # login/usuarios/(id_usuario)
    re_path(r'usuarios/(?P<pk>[0-9]+)/$',
        views.UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    re_path(r'deletaruser/(?P<pk>[0-9]+)/$',
        views.DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    re_path(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        views.EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),

    # selecionar empresa
    re_path(r'selecionarempresa/$', views.SelecionarMinhaEmpresaView.as_view(),
        name='selecionarempresaview'),
]

erp_mpro/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path, include
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('erp_mpro.apps.base.urls')),
    re_path(r'^login/', include('erp_mpro.apps.login.urls')),
    re_path(r'^cadastro/', include('erp_mpro.apps.cadastro.urls')),
    re_path(r'^fiscal/', include('erp_mpro.apps.fiscal.urls')),
    re_path(r'^vendas/', include('erp_mpro.apps.vendas.urls')),
    re_path(r'^compras/', include('erp_mpro.apps.compras.urls')),
    re_path(r'^financeiro/', include('erp_mpro.apps.financeiro.urls')),
    re_path(r'^estoque/', include('erp_mpro.apps.estoque.urls')),
    
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

erp_mpro/apps/cadastro/models/bancos.py
# -*- coding: utf-8 -*-

BANCOS = [
    ('001', '001 - BANCO DO BRASIL S.A.'),
    ('003', '003 - BANCO DA AMAZONIA S.A.'),
    ('004', '004 - BANCO DO NORDESTE DO BRASIL S.A.'),
    ('012', '012 - BANCO STANDARD DE INVESTIMENTOS S.A.'),
    ('014', '014 - NATIXIS BRASIL S.A. BANCO MÚLTIPLO'),
    ('019', '019 - BANCO AZTECA DO BRASIL S.A.'),
    ('021', '021 - BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO'),
    ('024', '024 - BANCO DE PERNAMBUCO S.A. - BANDEPE'),
    ('025', '025 - BANCO ALFA S.A.'),
    ('029', '029 - BANCO BANERJ S.A.'),
    ('031', '031 - BANCO BEG S.A.'),
    ('033', '033 - BANCO SANTANDER (BRASIL) S.A.'),
    ('036', '036 - BANCO BRADESCO BBI S.A.'),
    ('037', '037 - BANCO DO ESTADO DO PARÁ S.A.'),
    ('040', '040 - BANCO CARGILL S.A.'),
    ('041', '041 - BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.'),
    ('044', '044 - BANCO BVA S.A.'),
    ('045', '045 - BANCO OPPORTUNITY S.A.'),
    ('047', '047 - BANCO DO ESTADO DE SERGIPE S.A.'),
    ('062', '062 - HIPERCARD BANCO MÚLTIPLO S.A.'),
    ('063', '063 - BANCO IBI S.A. - BANCO MÚLTIPLO'),
    ('065', '065 - BANCO LEMON S.A.'),
    ('066', '066 - BANCO MORGAN STANLEY S.A.'),
    ('069', '069 - BPN BRASIL BANCO MÚLTIPLO S.A.'),
    ('070', '070 - BRB - BANCO DE BRASILIA S.A.'),
    ('072', '072 - BANCO RURAL MAIS S.A.'),
    ('073', '073 - BB BANCO POPULAR DO BRASIL S.A.'),
    ('074', '074 - BANCO J. SAFRA S.A.'),
    ('075', '075 - BANCO CR2 S/A'),
    ('076', '076 - BANCO KDB DO BRASIL S.A.'),
    ('077', '077 - BANCO INTERMEDIUM S/A'),
    ('078', '078 - BES INVESTIMENTO DO BRASIL S.A. - BANCO DE INVESTIMENTO'),
    ('079', '079 - JBS BANCO S/A'),
    ('081', '081 - CONCÓRDIA BANCO S.A.'),
    ('082', '082 - BANCO TOPÁZIO S.A.'),
    ('083', '083 - BANCO DA CHINA BRASIL S.A'),
    ('096', '096 - BANCO BM&F DE SERVIÇOS DE LIQUIDAÇÃO E CUSTÓDIA S.A.'),
    ('104', '104 - CAIXA ECONOMICA FEDERAL'),
    ('107', '107 - BANCO BBM S/A'),
    ('151', '151 - BANCO NOSSA CAIXA S.A.'),
    ('184', '184 - BANCO ITAÚ BBA S.A.'),
    ('204', '204 - BANCO BRADESCO CARTÕES S.A.'),
    ('208', '208 - BANCO UBS PACTUAL S.A.'),
    ('212', '212 - BANCO MATONE S.A.'),
    ('213', '213 - BANCO ARBI S.A.'),
    ('214', '214 - BANCO DIBENS S.A.'),
    ('215', '215 - BANCO COMERCIAL E DE INVESTIMENTO SUDAMERIS S.A.'),
    ('217', '217 - BANCO JOHN DEERE S.A.'),
    ('218', '218 - BANCO BONSUCESSO S.A.'),
    ('222', '222 - BANCO CALYON BRASIL S.A.'),
    ('224', '224 - BANCO FIBRA S.A.'),
    ('225', '225 - BANCO BRASCAN S.A.'),
    ('229', '229 - BANCO CRUZEIRO DO SUL S.A.'),
    ('230', '230 - UNICARD BANCO MÚLTIPLO S.A.'),
    ('233', '233 - BANCO GE CAPITAL S.A.'),
    ('237', '237 - BANCO BRADESCO S.A.'),
    ('241', '241 - BANCO CLASSICO S.A.'),
    ('243', '243 - BANCO MÁXIMA S.A.'),
    ('246', '246 - BANCO ABC BRASIL S.A.'),
    ('248', '248 - BANCO BOAVISTA INTERATLANTICO S.A.'),
    ('249', '249 - BANCO INVESTCRED UNIBANCO S.A.'),
    ('250', '250 - BANCO SCHAHIN S.A.'),
    ('254', '254 - PARANÁ BANCO S.A.'),
    ('260', '260 - NU PAGAMENTOS S.A.'),
    ('263', '263 - BANCO CACIQUE S.A.'),
    ('265', '265 - BANCO FATOR S.A.'),
    ('266', '266 - BANCO CEDULA S.A.'),
    ('300', '300 - BANCO DE LA NACION ARGENTINA'),
    ('318', '318 - BANCO BMG S.A.'),
    ('320', '320 - BANCO INDUSTRIAL E COMERCIAL S.A.'),
    ('341', '341 - BANCO ITAÚ S.A.'),
    ('366', '366 - BANCO SOCIETE GENERALE BRASIL S.A.'),
    ('370', '370 - BANCO WESTLB DO BRASIL S.A.'),
    ('376', '376 - BANCO J.P. MORGAN S.A.'),
    ('389', '389 - BANCO MERCANTIL DO BRASIL S.A.'),
    ('394', '394 - BANCO FINASA BMC S.A.'),
    ('399', '399 - HSBC BANK BRASIL S.A. - BANCO MULTIPLO'),
    ('409', '409 - UNIBANCO-UNIAO DE BANCOS BRASILEIROS S.A.'),
    ('412', '412 - BANCO CAPITAL S.A.'),
    ('422', '422 - BANCO SAFRA S.A.'),
    ('453', '453 - BANCO RURAL S.A.'),
    ('456', '456 - BANCO DE TOKYO-MITSUBISHI UFJ BRASIL S/A'),
    ('464', '464 - BANCO SUMITOMO MITSUI BRASILEIRO S.A.'),
    ('473', '473 - BANCO CAIXA GERAL - BRASIL S.A.'),
    ('477', '477 - CITIBANK N.A.'),
    ('479', '479 - BANCO ITAUBANK S.A.'),
    ('487', '487 - DEUTSCHE BANK S.A. - BANCO ALEMAO'),
    ('488', '488 - JPMORGAN CHASE BANK, NATIONAL ASSOCIATION'),
    ('492', '492 - ING BANK N.V.'),
    ('494', '494 - BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY'),
    ('495', '495 - BANCO DE LA PROVINCIA DE BUENOS AIRES'),
    ('505', '505 - BANCO CREDIT SUISSE (BRASIL) S.A.'),
    ('600', '600 - BANCO LUSO BRASILEIRO S.A.'),
    ('604', '604 - BANCO INDUSTRIAL DO BRASIL S.A.'),
    ('610', '610 - BANCO VR S.A.'),
    ('611', '611 - BANCO PAULISTA S.A.'),
    ('612', '612 - BANCO GUANABARA S.A.'),
    ('613', '613 - BANCO PECUNIA S.A.'),
    ('623', '623 - BANCO PANAMERICANO S.A.'),
    ('626', '626 - BANCO FICSA S.A.'),
    ('630', '630 - BANCO INTERCAP S.A.'),
    ('633', '633 - BANCO RENDIMENTO S.A.'),
    ('634', '634 - BANCO TRIANGULO S.A.'),
    ('637', '637 - BANCO SOFISA S.A.'),
    ('638', '638 - BANCO PROSPER S.A.'),
    ('641', '641 - BANCO ALVORADA S.A.'),
    ('643', '643 - BANCO PINE S.A.'),
    ('652', '652 - ITAÚ UNIBANCO BANCO MÚLTIPLO S.A.'),
    ('653', '653 - BANCO INDUSVAL S.A.'),
    ('654', '654 - BANCO A.J. RENNER S.A.'),
    ('655', '655 - BANCO VOTORANTIM S.A.'),
    ('707', '707 - BANCO DAYCOVAL S.A.'),
    ('719', '719 - BANIF - BANCO INTERNACIONAL DO FUNCHAL (BRASIL), S.A.'),
    ('721', '721 - BANCO CREDIBEL S.A.'),
    ('734', '734 - BANCO GERDAU S.A'),
    ('735', '735 - BANCO POTTENCIAL S.A.'),
    ('738', '738 - BANCO MORADA S.A'),
    ('739', '739 - BANCO BGN S.A.'),
    ('740', '740 - BANCO BARCLAYS S.A.'),
    ('741', '741 - BANCO RIBEIRAO PRETO S.A.'),
    ('743', '743 - BANCO SEMEAR S.A.'),
    ('745', '745 - BANCO CITIBANK S.A.'),
    ('746', '746 - BANCO MODAL S.A.'),
    ('747', '747 - BANCO RABOBANK INTERNATIONAL BRASIL S.A.'),
    ('748', '748 - BANCO COOPERATIVO SICREDI S.A.'),
    ('749', '749 - BANCO SIMPLES S.A.'),
    ('751', '751 - DRESDNER BANK BRASIL S.A. BANCO MULTIPLO'),
    ('752', '752 - BANCO BNP PARIBAS BRASIL S.A.'),
    ('753', '753 - NBC BANK BRASIL S. A. - BANCO MÚLTIPLO'),
    ('756', '756 - BANCO COOPERATIVO DO BRASIL S.A. - BANCOOB'),
    ('757', '757 - BANCO KEB DO BRASIL S.A.'),
]

erp_mpro/apps/cadastro/models/cliente.py
# -*- coding: utf-8 -*-

from django.db import models

from decimal import Decimal

from .base import Pessoa

INDICADOR_IE_DEST = [
    ('1', 'Contribuinte ICMS'),
    ('2', 'Contribuinte isento de Inscrição'),
    ('9', 'Não Contribuinte'),
]


class Cliente(Pessoa):
    limite_de_credito = models.DecimalField(
        max_digits=15, decimal_places=2, default=Decimal('0.00'), null=True, blank=True)
    indicador_ie = models.CharField(
        max_length=1, choices=INDICADOR_IE_DEST, default='9')
    id_estrangeiro = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        verbose_name = "Cliente"

erp_mpro/apps/cadastro/models/fornecedor.py
# -*- coding: utf-8 -*-

from django.db import models

from .base import Pessoa


class Fornecedor(Pessoa):
    ramo = models.CharField(max_length=64, null=True, blank=True)

    class Meta:
        verbose_name = "Fornecedor"

erp_mpro/models.py
from django.db import models

# Create your models here.

erp_mpro/templates/estoque/consulta/consulta_estoque.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
  
    <div class="title-header">
      <h2>ESTOQUE</h2>
    </div>
    
    {% include 'base/msg_sucesso.html' %}
    {% include 'base/msg_error.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        
        <div class="header">
          <h2>
            {{title_complete}}
          </h2>
        </div>

        <!-- Body -->
        <div class="body">

          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="row" style="border-bottom: 1px solid #afabab;margin-bottom: 17px;">
              <h4 style="border-bottom: 1px solid #afabab;">Filtrar</h4>
              <form role="form" action="{% url 'estoque:consultaestoqueview' %}" method="get">
              {% csrf_token %}
                <div class="col-sm-5">
                  <div class="form-group">
                    <div class="form-line">
                      <label>Produto</label>
                      <select class="form-control" id="produto_id" name="produto">
                        <option value="">Todos</option>
                      {% for produto in todos_produtos %}
                        <option value="{{ produto.id }}" {% if produto.id|stringformat:"s" == request.GET.produto %}selected{% endif %}>{{ produto }}</option>
                      {% endfor %}
                      </select>
                    </div>
                  </div>
                </div>

                <div class="col-sm-5">
                  <div class="form-group">
                    <div class="form-line">
                      <label>Local de estoque</label>
                      <select class="form-control" id="local_id" name="local">
                        <option value="">Todos</option>
                      {% for local in todos_locais %}
                          <option value="{{ local.id }}" {% if local.id|stringformat:"s" == request.GET.local %}selected{% endif %}>{{ local }}</option>
                      {% endfor %}
                      </select>
                    </div>
                  </div>
                </div>

                <div class="col-sm-2">
                    <button style="margin-top:25px;" class="btn btn-primary foot-btn" type="submit">BUSCAR</button>
                </div>

              </form>

            </div>

            <div class="table-responsive">
              <table class="table table-bordered table-striped lista-table">
                <thead>
                  <tr>
                    <th>Código</th>
                    <th>Produto</th>
                    <th>Categoria</th>
                    <th>Qtd. Atual</th>
                    <th>Qtd. Mínima</th>
                    <th>Vl. Unitário</th>
                  </tr>
                </thead>

                <tbody>
                  {% for produto in produtos_filtrados %}
                  <tr colspan="6" style="font-weight: bolder;background-color: #d2dee0;" class="prevent-click-row" data-toggle="collapse" data-target=".accordion-{{produto.id}}">
                    <td>{{produto.codigo}}</td>
                    <td>{{produto}}</td>
                    <td>{% if produto.categoria %}{{produto.categoria}}{% endif %}</td>
                    <td>{{produto.estoque_atual}}</td>
                    <td>{{produto.estoque_minimo}}</td>
                    <td>{{produto.venda}}</td>
                  </tr>
                    <tr colspan="6" class="plano-subgrupo-row accordion-{{produto.id}} in">
                      <th colspan="3" style="font-weight: bolder; border-bottom-color: darkblue;">Local</th>
                      <th colspan="3" style="font-weight: bolder; border-bottom-color: darkblue;">Quantidade</th>
                    </tr>
                    {% for pe in produto.produto_estocado.all %}
                    <tr class="plano-subgrupo-row accordion-{{produto.id}} in">
                      <td colspan="3">{{pe.local}}</td>
                      <td colspan="3">{{pe.quantidade}}</td>
                    </tr>
                    {% endfor %}
                  {% endfor %}
                </tbody>
              </table>
            </div>
  
          </div>

        </div>
        <!-- #Body -->

      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'base/load_jqueryui.html' %}

  {% include 'base/datepicker_js.html' %}

  {% include 'base/tooltip_js.html' %}

   <script type="text/javascript">
    $.Admin.fluxoCaixa.init();
  </script>
  
{% endblock %}